"""Initial migration

Revision ID: 0c222da05aac
Revises:
Create Date: 2025-09-16 10:18:48.558305

"""

from typing import Sequence, Union

from token_service.store.orm import PendulumDateTime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c222da05aac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Base tables
    op.create_table(
        "user",
        sa.Column("uid", sa.String(length=32)),
        sa.Column("is_admin", sa.Boolean()),
        sa.PrimaryKeyConstraint("uid"),
    )

    op.create_table(
        "group",
        sa.Column("name", sa.String(length=32)),
        sa.PrimaryKeyConstraint("name"),
    )

    op.create_table(
        "scope",
        sa.Column("name", sa.String(length=32)),
        sa.Column("description", sa.String(length=128)),
        sa.PrimaryKeyConstraint("name"),
    )

    # Dependent tables
    op.create_table(
        "token",
        sa.Column("id", sa.String(length=36)),
        sa.Column("name", sa.String(length=256)),
        sa.Column("user_uid", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=128), nullable=False),
        sa.Column("iat", PendulumDateTime(), nullable=False),
        sa.Column("nbf", PendulumDateTime(), nullable=False),
        sa.Column("exp", PendulumDateTime(), nullable=False),
        sa.Column("paths", sa.JSON(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("last_used", PendulumDateTime()),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_uid"], ["user.uid"]),
        sa.UniqueConstraint("value"),
    )

    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), sa.Identity()),
        sa.Column(
            "event",
            sa.Enum("AUTH", "CREATION", "DELETION", "EXPIRATION", name="auditevent"),
            nullable=False,
        ),
        sa.Column(
            "auth_failure_reason",
            sa.Enum(
                "NOT_YET_VALID",
                "EXPIRED",
                "INVALID",
                "NONEXISTENT",
                "ACCOUNT_INVALID",
                name="authfailurereason",
            ),
        ),
        sa.Column("request_method", sa.String(length=32), nullable=False),
        sa.Column("token_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", PendulumDateTime(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("destination", sa.String(length=32), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["token_id"], ["token.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # Association tables
    op.create_table(
        "token_scope_association",
        sa.Column("token_id", sa.String(length=36)),
        sa.Column("scope_name", sa.String(length=32)),
        sa.ForeignKeyConstraint(["token_id"], ["token.id"]),
        sa.ForeignKeyConstraint(["scope_name"], ["scope.name"]),
        sa.PrimaryKeyConstraint("token_id", "scope_name"),
    )

    op.create_table(
        "user_group_association",
        sa.Column("user_uid", sa.String(length=32)),
        sa.Column("group_name", sa.String(length=32)),
        sa.ForeignKeyConstraint(["user_uid"], ["user.uid"]),
        sa.ForeignKeyConstraint(["group_name"], ["group.name"]),
        sa.PrimaryKeyConstraint("user_uid", "group_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop association tables first
    op.drop_table("user_group_association")
    op.drop_table("token_scope_association")

    # Then dependent tables
    op.drop_table("audit")
    op.drop_table("token")

    # Then base tables
    op.drop_table("scope")
    op.drop_table("group")
    op.drop_table("user")
