"""remove unique constraint on duid

Revision ID: 0e1ef5458f74
Revises: db5ff1ca50e2
Create Date: 2025-12-29 14:01:04.854491

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0e1ef5458f74'
down_revision: Union[str, Sequence[str], None] = 'db5ff1ca50e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_duid_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_duid_key'), 'user', ['duid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
