"""add session marker

Revision ID: 237acb29e460
Revises: fb5b063e37a1
Create Date: 2026-03-22 18:25:30.904454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237acb29e460'
down_revision: Union[str, Sequence[str], None] = 'fb5b063e37a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('session', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'session')
    # ### end Alembic commands ###
