"""add_admin_role

Revision ID: 445b74e0a999
Revises: 8823466cec2e
Create Date: 2026-02-03 17:00:06.340408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445b74e0a999'
down_revision: Union[str, Sequence[str], None] = '8823466cec2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    adminrole_enum = sa.Enum('ANY', 'IMPERSONATION', 'IDENTITY', 'NONE', name='adminrole')
    adminrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'admin_token',
        sa.Column('role', adminrole_enum, nullable=False, server_default=sa.text("'NONE'")),
    )
    op.alter_column('admin_token', 'role', server_default=None, existing_type=adminrole_enum)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_token', 'role')
    adminrole_enum = sa.Enum('ANY', 'IMPERSONATION', 'IDENTITY', 'NONE', name='adminrole')
    adminrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
