"""update token unique constraint for subtokens

Revision ID: 450dd1ce1ff1
Revises: 237acb29e460
Create Date: 2026-04-13 18:23:53.249177

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '450dd1ce1ff1'
down_revision: Union[str, Sequence[str], None] = '237acb29e460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

constraint_name = "uq_token_user_name_parent_id_external_id"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_token_user_name'), 'token', type_='unique')
    op.create_unique_constraint(constraint_name, 'token', ['user_uid', 'name', 'parent_id', 'external_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name, 'token', type_='unique')
    op.create_unique_constraint(op.f('uq_token_user_name'), 'token', ['user_uid', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
