"""add user_uid unique constraint column to token table

Revision ID: 50db14aea8e8
Revises: 0c222da05aac
Create Date: 2025-09-16 15:34:24.610996

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "50db14aea8e8"
down_revision: Union[str, Sequence[str], None] = "0c222da05aac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_token_user_name", "token", ["user_uid", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_token_user_name", "token", type_="unique")
    # ### end Alembic commands ###
