"""add admin token table and add admin_token_id to token table

Revision ID: 8823466cec2e
Revises: 0e1ef5458f74
Create Date: 2026-01-15 13:53:20.355238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8823466cec2e'
down_revision: Union[str, Sequence[str], None] = '0e1ef5458f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_token',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('value', sa.String(length=128), nullable=False),
        sa.Column('remote_id', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('remote_id'),
        sa.UniqueConstraint('value')
    )
    op.add_column('token', sa.Column('admin_token_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'token', 'admin_token', ['admin_token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'admin_token_id')
    op.drop_table('admin_token')
    # ### end Alembic commands ###
