"""add rotatable attribute to token

Revision ID: bc91b45c54bf
Revises: 450dd1ce1ff1
Create Date: 2026-04-22 11:14:55.309768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc91b45c54bf'
down_revision: Union[str, Sequence[str], None] = '450dd1ce1ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('rotatable', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'rotatable')
    # ### end Alembic commands ###
