"""Add duid to user

Revision ID: db5ff1ca50e2
Revises: 50db14aea8e8
Create Date: 2025-12-22 17:02:36.407510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5ff1ca50e2'
down_revision: Union[str, Sequence[str], None] = '50db14aea8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('duid', sa.String(length=128), nullable=True))
    op.create_unique_constraint("user_duid_key", 'user', ['duid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_duid_key", 'user', type_='unique')
    op.drop_column('user', 'duid')
    # ### end Alembic commands ###
