"""add subtoken fields

Revision ID: fb5b063e37a1
Revises: 445b74e0a999
Create Date: 2026-03-09 15:42:04.664731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5b063e37a1'
down_revision: Union[str, Sequence[str], None] = '445b74e0a999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

fk_constraint_name = "token_parent_id_fkey"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.add_column('token', sa.Column('external_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(fk_constraint_name, 'token', 'token', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(fk_constraint_name, 'token', type_='foreignkey')
    op.drop_column('token', 'external_id')
    op.drop_column('token', 'parent_id')
    # ### end Alembic commands ###
