config:
  logLevel: "INFO"
  server:
    host: "0.0.0.0"
    port: 8080
    loop: "asyncio"
  db:
    url: "postgresql+psycopg2://tokenServiceUser@token-service-db:5432/tokenServiceDB"
  auth:
    authlib_oidc:
      url: "https://lc.llnl.gov/token-service"
      discovery_url: "https://scf-auth.llnl.gov/.well-known/openid-configuration"
      session_config:
        domain: "lc.llnl.gov"
        same_site: "lax"

resources:
  app:
    requests:
      cpu: 300m
      memory: 512Mi
  db: {}

namespace: token-service-prod

ingress:
  enabled: true
  hosts:
    - host: lc.llnl.gov
      paths:
        - path: /token-service
          pathType: Prefix
          port:
            name: http
    - host: token-service-prod.apps.scf-lc.llnl.gov
      paths:
        - path: /token-service
          pathType: Prefix
          port:
            name: http

image:
  db:
    repository: image-registry.openshift-image-registry.svc:5000/openshift/postgres
    pullPolicy: IfNotPresent
    tag: "16-bullseye"