apiVersion: v1
kind: ConfigMap
metadata:
  name: token-service-config
data:
  # Open Telemetry
  OTEL_SERVICE_NAME: {{ include "token-service.name" . }}
  OTEL_TRACES_EXPORTER: {{ .Values.config.otel.traces_exporter | quote }}
  OTEL_METRICS_EXPORTER: {{ .Values.config.otel.metrics_exporter | quote }}
  OTEL_LOGS_EXPORTER: {{ .Values.config.otel.logs_exporter | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.config.otel.otlp_traces_endpoint | quote }}
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: {{ .Values.config.otel.otlp_metrics_endpoint | quote }}
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: {{ .Values.config.otel.otlp_logs_endpoint | quote }}

  DYNACONF_log_level: {{ .Values.config.logLevel | quote }}
  DYNACONF_root_path: {{ .Values.config.root_path | quote }}

  # Server
  DYNACONF_SERVER__host: {{ .Values.config.server.host | quote }}
  DYNACONF_SERVER__port: {{ .Values.config.server.port | quote }}
  DYNACONF_SERVER__loop: {{ .Values.config.server.loop | quote }}

  # DB
  DYNACONF_DB__url: {{ .Values.config.db.url | quote }}
  DB_SERVICE_NAME: {{ include "token-service.db-fullname" . | quote }}

  # auth
  DYNACONF_AUTH__auth_name: {{ .Values.config.auth.auth_name | quote }}

  # oidc
  DYNACONF_AUTH__authlib_oidc__url: {{ .Values.config.auth.authlib_oidc.url | quote }}
  {{- with .Values.config.auth.authlib_oidc.session_config }}
  DYNACONF_AUTH__authlib_oidc__session_config__session_cookie: {{ .session_cookie }}
  DYNACONF_AUTH__authlib_oidc__session_config__same_site: {{ .same_site }}
  DYNACONF_AUTH__authlib_oidc__session_config__https_only: {{ .https_only | quote }}
  DYNACONF_AUTH__authlib_oidc__session_config__max_age: {{ .max_age | quote }}

  {{- if .domain }}
  DYNACONF_AUTH__authlib_oidc__session_config__domain: {{ .domain | quote }}
  {{- end }}

  {{- end }}
  DYNACONF_AUTH__authlib_oidc__strategy_name: {{ .Values.config.auth.authlib_oidc.strategy_name | quote }}
  DYNACONF_AUTH__authlib_oidc__discovery_url: {{ .Values.config.auth.authlib_oidc.discovery_url | quote }}
  DYNACONF_AUTH__authlib_oidc__redirect_uri: {{ .Values.config.auth.authlib_oidc.redirect_uri | quote }}

  # JWT
  DYNACONF_AUTH__jwt__alg: {{ .Values.config.auth.jwt.alg | quote }}
  DYNACONF_AUTH__jwt__active_kid: {{ .Values.config.auth.jwt.active_kid | quote }}

  # OAUTH JWT
  DYNACONF_AUTH__oauth_jwt__jwks_url: {{ .Values.config.auth.oauth_jwt.jwks_url | quote }}

  # Token
  DYNACONF_TOKEN__session_name: {{ .Values.config.token.session_name | quote }}
  DYNACONF_TOKEN__session_lifetime_seconds: {{ .Values.config.token.session_lifetime_seconds | quote }}
  DYNACONF_TOKEN__max_lifetime_days: {{ .Values.config.token.max_lifetime_days | quote }}
