apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-service.fullname" . }}
  labels:
    {{- include "token-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.config.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "token-service.selectorLabels" . | nindent 4 }}
