apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-service.db-fullname" . }}
  labels:
    {{- include "token-service.labels" . | nindent 4 }}-db
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.port }}
  selector:
    {{- include "token-service.selectorLabels" . | nindent 4 }}-db
