apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.saDB.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- with .Values.serviceAccount.saDB.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
