#
name: Create and publish a Docker image

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # https://github.com/actions/checkout/commit/3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      # https://github.com/docker/login-action/commit/371161bbe7024a29a25c5e19bfcbc0804fe9ad2c
      - name: Log in to the Container registry
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/metadata-action/commit/dc802804100637a589fabce1cb79ff13a1411302
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # https://github.com/docker/build-push-action/commit/53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # github.com/actions/attest/commit/f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6
      - name: Generate artifact attestation
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
