name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install UV
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync -p 3.11
      - name: Build Wheels
        run: uv tool run hatch build
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: Release
    needs:
      - build
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
